### ISSUE TITLE
ps2 esp32 psp

### ISSUE THREAD

**Issue by amilton33** [davidxgames/ESP32-FLASH-ONLINE#1]
Hello, you made a project of a consolized psp?

**Comment by davidxgames** [comment]
> Hola, hiciste un proyecto de una psp consolada?

Yes, I managed to do it, I did it using esp32. I did it in two ways, one using blueretro and another bluepad32. I just haven't published it on my youtube channel yet.

**Comment by Bma36** [comment]
amazing, sorry for contacting you here, I also want to do the project but I have some questions, did you use the same PCB from the original project with the esp32? If so, did you have to adapt the pinout? If it's not bothersome, would you have any contact to talk better, email, telegram, whatsapp, discord?

**Comment by davidxgames** [comment]
> increíble, disculpa por contactarte aquí, yo también quiero hacer el proyecto pero tengo algunas preguntas, usaste la misma PCB del proyecto original con el esp32? Si es así, ¿tuviste que adaptar el pinout? Si no es molesto, tendrías algún contacto para hablar mejor, email, telegram, whatsapp, discord?

https://www.youtube.com/channel/UCusIoB_4vKBwBtdc81PolUw
twitter @XGAMES_VJ
